### ISSUE TITLE
arch: mips64el build support

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-core#41]
There are several things to do still.

- [x] Come up with a set of compiler flags specific to mips64el.
- [x] Architectural build config for mips64el.
- [x] Tests.

**Comment by jyhi** [comment]
Currently the compiler flags (except those defined in `autobuild3` by default) are

```
-mabi=64 -march=mips64r2 -mtune=loongson3a #-mno-branch-likely -fprefetch-loop-arrays
```

**(Update: No longer using `-fprefetch-loop-arrays`. See reply below.)**

**(Update: No longer using `-mno-branch-likely`. See reply below.)**

Thus, the goal of this port is:
1. MIPS64 port, at least on `mips64 rel 2` platform, and tune for Loongson 3A
   - According to [one post from Imagination Technology](https://imgtec.com/blog/loongson-mips64-processors-performance-barrier/), Loongson 3A-2000 supports MIPS64 release 3 ISA (**Update: we know from Loongson codes that this is not true.**), yet according to [Loongson 3A user manual (PDF)](http://loongson.cn/uploadfile/cpu/3A2000/Loongson3A2000_user2_V1.02.pdf) and some Internet posts, we find that Loongson 3A only supports MIPS64r2 (also, the `EI/DI` (Enable Interrupt / Disable Interrupt) instructions are not behaved as standard says, but this does no harm to software if using `-march=mips*`). Besides, for the following reasons, we decided to build with `-march=mips64r2`:
     - Debian and Fedora are porting to `mips64r2` too;
     - Some software like `ffmpeg` have some parts written in `mips64r2` assembly language.
2. N64 ABI

Several platform-specific flags:
- ~~`-mno-abicall`: "Generate code that is suitable for SVR4-style (System V Rev 4) dynamic objects." From some tests we can discover that it does reduce code size and increase efficiency.~~
  - **Errata: `-fPIC` needs `-mabicalls`. Not using this option anymore.**
- `-mno-branch-likely`: "Disable use of Branch Likely instructions, regardless of the default for the selected architecture. By default, Branch Likely instructions may be generated if they are supported by the selected architecture. An exception is for the MIPS32 and MIPS64 architectures and processors that implement those architectures; for those, Branch Likely instructions are not be generated by default because the MIPS32 and MIPS64 architectures specifically deprecate their use."
  - According to [Wikipedia](https://en.wikipedia.org/wiki/MIPS_instruction_set#MIPS32.2FMIPS64_Release_6), _branch likely_ instructions are removed in MIPS64r6, and is deprecated in releases prior to r6.
  - According to [one performance optimization guide for Loongson 3A from Loongnix (PDF)](http://ftp.loongnix.org/doc/08Performance%20Optimization/Loongson3A%20Performance%20Optimization.pdf), `gcc` will work better with `-mno-branch-likely`.（“事实上，我们发现带有 -mno-branch-likely 选项的 gcc 通常会工作得更好。”）

Some optimization flags:
- ~~`-fprefetch-loop-arrays`: "If supported by the target machine, generate instructions to prefetch memory to improve the performance of loops that access large arrays."~~
  - According to [the official GCC manual](https://gcc.gnu.org/onlinedocs/gcc-6.2.0/gcc/Optimize-Options.html), "this option may generate better or worse code; results are highly dependent on the structure of loops within the source code". This is a strategy of "space for time". **Still needs discussion.**
  - According to [Loongson 3A user manual (PDF)](http://loongson.cn/uploadfile/cpu/3A2000/Loongson3A2000_user2_V1.02.pdf) (table 2-12), prefetch instructions are defined in MIPS32 ISA. We think prefetch has been implemented by all MIPS processors (at least, MIPS64r2), so we open this optimization.
  - Also, according to [GNU GCC's prefetch project page](https://gcc.gnu.org/projects/prefetch.html), prefetch should be on x86 processors with SSE too.
  - **Update: we think this 1) should not be a platform-specific flag, and 2) increases unnecessary overheads, so we delete this flag from our Autobuild configuration. See reply below.**

Also, there are some optimization flags:
- have already been the default for `autobuild3` (say, `-ftree-vectorize` and `-O2`, which enable almost all optimizations)
- still needs further discussion, like some optimizations that are opened along with PGO (like `-ftracer`).

**Comment by MingcongBai** [comment]
Mostly good... Just wanted to point some points out/clarify.

> Some software like ffmpeg have some parts written in mips64r2 assembly language.

There is MIPS64r1 support too, to be fair. But there is no real processor produced with that specification...

> -fprefetch-loop-arrays: "If supported by the target machine, generate instructions to prefetch memory to improve the performance of loops that access large arrays."

This flag would be used on all architectures if ever enabled. This is not exactly a MIPS-specific flag.
- https://gcc.gnu.org/projects/prefetch.html
- http://ctuning.org/dissemination/grow10-03.pdf

> still needs further discussion, like some optimizations that are opened along with PGO (like -ftracer).

"Perform tail duplication to enlarge superblock size. This transformation simplifies the control flow of the function allowing other optimizations to do better job. "

An aid to other optimization perhaps?

**Comment by jyhi** [comment]
From the `configure` line in `gcc -v` in Loongnix, we also find a `-with-long-double-128`.

According to [GCC installation guide](https://gcc.gnu.org/install/configure.html): "Specify if long double type should be 128-bit by default on selected GNU/Linux architectures. If using --without-long-double-128, long double will be by default 64-bit, the same as double type. When neither of these configure options are used, the default will be 128-bit long double when built against GNU C Library 2.4 and later, 64-bit long double otherwise." We should have a `glibc` 2.4+.

**Comment by jyhi** [comment]
> This is not exactly a MIPS-specific flag.

@MingcongBai It is optimization flags, not in the "platform-specific" section.

**Comment by MingcongBai** [comment]
> @MingcongBai It is optimization flags, not in the "platform-specific" section.

My bad.

**Comment by MingcongBai** [comment]
> From the configure line in gcc -v in Loongnix, we also find a -with-long-double-128.

Which is also opened for the `ppc64` architecture.

**Comment by MingcongBai** [comment]
If that's the case, I think at least on the MIPS64 part, all flags are ready to be deployed?

**Comment by jyhi** [comment]
> Which is also opened for the ppc64 architecture.

@MingcongBai 

> the default will be 128-bit long double when built against GNU C Library 2.4 and later

-- https://gcc.gnu.org/install/configure.html

**Comment by jyhi** [comment]
> I think at least on the MIPS64 part, all flags are ready to be deployed?

Yes. I am now still preparing the Loongson 3A-2000 buildbot.

**Comment by MingcongBai** [comment]
Okay, checking the first tick.

**Comment by jyhi** [comment]
From GNU's `config.sub` I composed some available machine name strings.
- Generally, `mips64{,el}-aosc-linux-gnu` should be good to use.
- To explicitly specify the "MIPS64**r2**", `mipsisa64r2{,el}-aosc-linux-gnu` is also correct, but it is ~~a little bit~~ too long.
- To explicitly specify the ABI (we use N64), `mips64{,el}-aosc-linux-gnuabin64` is also correct.

**Comment by MingcongBai** [comment]
> To explicitly specify the ABI (we use N64), mips64{,el}-aosc-linux-gnuabin64 is also correct.

I did that for the N32 port (RIP), I guess specifying it might be a good idea. Is there a possibility that MIPS64 uses N32?

**Comment by jyhi** [comment]
> Is there a possibility that MIPS64 uses N32?

Yes. N32 and N64 are both for **only** 64-bits, while O32 is for 32-bits.

**Comment by jyhi** [comment]
> N32 and N64 are both for only 64-bits

Some clarification. N32 is a derivative of N64, with the only difference of length of pointers (N32 uses 32-bits long pointer while N64 uses 64-bits long pointer). O32 is the real 32-bits mode.

https://www.linux-mips.org/wiki/WhatsWrongWithO32N32N64

**Comment by MingcongBai** [comment]
In this case I would suggest explicitly declare N64.

**Comment by jyhi** [comment]
Then `mips64el-aosc-linux-gnuabin64`?

**Comment by MingcongBai** [comment]
Yep...

**Comment by bobcao3** [comment]
N32 will work better if the platform/software package does not need long pointers (which is extremely long and costly in N64). Also O32 software should be able to recompile to N32 easily.

**Comment by Artoria2e5** [comment]
@bobcao3 Sounds like some argument for x32. Well it's true that you don't get that much RAM on current MIPS machines…

**Comment by jyhi** [comment]
> Well it's true that you don't get that much RAM on current MIPS machines…

We have a Loongson 3A-2000 machine with 8GB RAM.

@bobcao3 is right. But this should be related to how we position our MIPS64 port -- will it run on embedded systems, which usually don't have much memory? The fact is that currently MIPS processors aren't common on PCs.

**Comment by jyhi** [comment]
Errata: **Not using `-mno-abicalls` anymore.** PIC needs `-mabicalls`.

**Comment by MingcongBai** [comment]
N32 was not shown strong interest by Debian or Fedora, something to look out for:
- What would happen if we choose to go down the N32 path (how much trouble)?
- What does this lack of interest reflect (what is wrong)?

**Comment by jyhi** [comment]
@MingcongBai At least we know that N32 ABI uses 32-bit pointer, which means it can only reach `0xffffffff`(4GiB).

**Comment by MingcongBai** [comment]
> @MingcongBai At least we know that N32 ABI uses 32-bit pointer, which means it can only reach 0xffffffff(4GiB).

That's a major set-back then - inhibiting to say the least, as MIPS64-based workstation is really where the whole new architecture is at.

**Comment by Artoria2e5** [comment]
> https://www.linux-mips.org/wiki/WhatsWrongWithO32N32N64

My, their way of using MediaWiki really disgusts me…

**Comment by MingcongBai** [comment]
Indeed...

**Comment by Artoria2e5** [comment]
> An exception is for the MIPS32 and MIPS64 architectures and processors that implement those architectures; for those, Branch Likely instructions are not be generated by default because the MIPS32 and MIPS64 architectures specifically deprecate their use.
> 
> According to one performance optimization guide for Loongson 3A from Loongnix (PDF), gcc will work better with `-mno-branch-likely`.

How can gcc work better at all? `-mno-branch-likely` is the default for MIPS.

**Comment by jyhi** [comment]
@Artoria2e5 "By default, Branch Likely instructions may be generated if they are supported by the selected architecture."

**Comment by MingcongBai** [comment]
Inserting a suggestion here...

To be fair, N32 is more suitable **currently** if it would ever run on a pre LS3 class machine.

But if the port points at MIPS64r2 specifically, N64 could well be the most suitable here:
- We are left with LS3+ and Octeon processors, which are both micro-to-mini scaled computer processors - RAM is not that limited here.
- Most of the MIPS64 porting efforts, by Fedora, SUSE, and Debian (they are all not done with the port yet) chose N64, we could at least get some second hand info here - and upstream projects should have more interest in this ABI anyways.
- Heck, look into the future masters.

Admittedly that was a bit of a conformist talk, but I guess with limited man power, this could be our best bet on creating a good port. Don't even get me started on PPC and PPC64...

**Comment by MingcongBai** [comment]
> How can gcc work better at all? -mno-branch-likely is the default for MIPS.

This was only removed by MIPS64r6, r2 still has support for this, only marked deprecated.

**Comment by Artoria2e5** [comment]
@MingcongBai So I should blame gcc documentation for not considering MIPS64r2 one of MIPS64 architectures.

**Comment by MingcongBai** [comment]
Yep. I would say so.

**Comment by jyhi** [comment]
Confirming configurations:
- `gcc` flags (without `ab3` defaults): `-mabi=64 -march=mips64r2 -mtune=loongson3a -mno-branch-likely -fprefetch-loop-arrays`

Building will start soon.

**Comment by MingcongBai** [comment]
`mips64el` support added to Autobuild3 with AOSC-Dev/autobuild3@7271c3c26d9e3aca26454e1608d7acb2059be360 and AOSC-Dev/autobuild3@5de62d0f67cb7ddb1b0552d173b1ae6023e0a14e.

**Comment by Artoria2e5** [comment]
@MingcongBai (comment edited)

**Comment by MingcongBai** [comment]
@Artoria2e5 Sorry which one?

**Comment by MingcongBai** [comment]
MIPS64el support will be delayed for Core 4.2 as requested by @lmy441900 for time constraints.

**Comment by Artoria2e5** [comment]
[Loongson 3A tuning](https://github.com/gcc-mirror/gcc/blob/gcc-6_1_0-release/gcc/config/mips/mips-cpus.def#L167) actually seems to avoid branch-likely, and so does `mips64r2` generic tuning. Weird.

**Comment by MingcongBai** [comment]
Test results are self-evidence in the sense that we have already started building X11 support, and soon there will be full desktop support for MIPS64el. This is now marked done.

**Comment by jyhi** [comment]
## "See reply ~~below~~ HERE."

One more thing...

In practice we did not fully follow the discussion above. Autobuild flags are actually:

```
-mabi=64 -march=mips64r2 -mtune=loongson3a
```

That is, without `-fprefetch-loop-arrays` and `-mno-branch-likely`. See:

- AOSC-Dev/autobuild3#96.
- AOSC-Dev/autobuild3@4a38899945adf09552e5bdf337e52bfe8c99963f.

For GCC triplet, we selected `mips64el-aosc-linux-gnu` instead of `mips64el-aosc-linux-gnuabin64` (without the ABI prompt).

Updating discussions above.
