### ISSUE TITLE
binutils: switch back to ld.bfd as default

### ISSUE THREAD

**Issue by Icenowy** [AOSC-Dev/aosc-os-core#71]
Although Gold linker is said to have better effiency when linking, there's many low-level packages that cannot be built w/ Gold, even including the Linux kernel.

When the default linker is Gold, users will face mystery build error when trying to manual build these packages.

**Comment by Icenowy** [comment]
Linux kernel commit http://github.com/torvalds/linux/commit/75959d44f9dc8e44410667009724e4e238515502 starts to refuse Gold.

**Comment by xiangzhai** [comment]
How about LLD?

**Comment by Icenowy** [comment]
@xiangzhai LLVM is not part of AOSC OS Core, so impossible.

**Comment by LionNatsu** [comment]
The commit message says:
> So instead of dealing with attempts to duct tape gold support without
> understanding *the root cause* and without support from the gold folks, fail
> the build when gold is detected.

It seems like a temporary solution for a specific issue, instead of explicitly declaring a long-term goal to refuse it. However, outputs of two linkers completely compatible with each other, so nothing is stopping us to switch between them. Please correct me if I misunderstood anything.

**Comment by MingcongBai** [comment]
Fixed in 6346e0e46d1cb295a4af31af56e814db9e977615 and ea6338e6c2938d487897fbdcbf49000115c8d4d6. Closing.
